### ISSUE TITLE
Make sure that all images using cloudinary are properly sized

### ISSUE THREAD

**Issue by rantav** [reversim/reversim-summit-2020#50]
Images downloaded from cloudinary that aren't properly sized are disastrous. They don't only waste our user's bandwidth, but also kill our service at cloudinary and makes us have to pay plenty of $$$... 

- [ ] Go over all images `<img` tags and make sure that if they use an image loaded from the DB or any other image that could come from cloudinary, use the `image` function (see below) 
- [ ] Simply search for usages of the function `image` on the client code from the file images.js and make sure that when used, the `width` and `height` are correct (match the CSS or image width and height)

**Comment by yarivShamash** [comment]
Double checked, all OK!
