### ISSUE TITLE
Update timeline.js and related 

### ISSUE THREAD

**Issue by rantav** [reversim/reversim-summit-2020#52]
Update with the correct timeline

- [ ] **timeline.js**
- [ ] in **proposals.js**
```
export const CFP_ENDS = new Date(2019, 1, 28);
export const CFP_ENDS_STR = 'February 28th midnight UTC';
export const CFP_ENDS_STR_SHORT = 'Feb 28';
```
- [ ] **eventConfig.js**
```
  cfpStartDate: process.env.CFP_START_DATE ||  "2019-01-20",
  cfpEndDate: process.env.CFP_END_DATE || "2020-02-28",
  votingStartDate: process.env.VOTING_START_DATE || "2020-02-12",
  votingEndDate: process.env.VOTING_END_DATE || "2020-03-23",
  summitStartDate: process.env.SUMMIT_START_DATE || "2020-10-14",
```

**Comment by rantav** [comment]
See also https://github.com/reversim/reversim-summit-2020/pull/53

**Comment by yarivShamash** [comment]
Hey Ran I changed the dated to 2020 but they don't add up. The `CFP_END_DATE` has already passed and we haven't yet started the CFP.
In the spec file you noted the CFP starts at "Typically D-5M" so it should all be somewhere in May.
Should I open a PR and merge? 

Waiting on your replay :)

**Comment by rantav** [comment]
Yes, we haven't set the dates yet, but let's speculate and then fix when we have a proper date so: 

  CFP_START_DATE:  "2019-05-01",
  CFP_END_DATE: "2020-06-01",
  VOTING_START_DATE: "2020-06-14",
  VOTING_END_DATE: "2020-06-31",
  SUMMIT_START_DATE: "2020-10-14" // this we know...
